### ISSUE TITLE
Stats section suggestion

### ISSUE THREAD

**Issue by PleaseInsertNameHere** [PowerNukkitX/website#26]
I suggest adding a "more info" button below the stats section referring to bStats.

Also, the data is hardcoded right now, so a dynamic approach would be recommended.
*(data is public so you can load it client-side)*

Links:
* [PowerNukkitX bStats](https://bstats.org/plugin/server-implementation/PowerNukkitX/16708)
* [bStats REST API](https://bstats.org/help/rest-api)
* [PowerNukkitX API charts (JSON data)](https://bstats.org/api/v1/plugins/16708/charts/)

**Comment by AzaleeX** [comment]
this has been corrected it sends correctly
